import {type ResolvedThemeMode, type ThemeTokens} from '../types';

export const blue2024Theme: Record<ResolvedThemeMode, ThemeTokens> = {
    light: {
        id: 'blue-2024',
        mode: 'light',
        colors: {
            appBackground: '#EAF2FF',
            navigationBackground: '#43546E',
            navigationBorder: 'rgba(255, 255, 255, 0.08)',
            navigationActive: '#5B5FFF',
            navigationInactive: '#E2E8F0',
            navigationBackdrop: '#536176',
            navigationSurface: '#EDF4FF',
            navigationShadow: '#031633',
            navigationScrim: '#062556',
            menuBackground: '#5A6780',
            menuPanel: '#6A768D',
            sheetBackground: '#FFFFFF',
            sheetHandle: '#B6C7E3',
            headerActionBackground: '#F5F9FF',
            headerActionForeground: '#6A7EA3',
            surfacePrimary: '#FFFFFF',
            surfaceMuted: '#F5F9FF',
            surfaceAccent: '#D8E8FF',
            surfaceAccentStrong: '#0E5DCC',
            surfaceInverse: '#082F66',
            surfaceSuccess: '#DDF7E8',
            surfaceDanger: '#FCE1E1',
            surfaceWarning: '#FEECC7',
            textPrimary: '#0A1F44',
            textSecondary: '#29466F',
            textMuted: '#5B769D',
            textInverse: '#F4F8FF',
            textBrand: '#8FB6F0',
            textSuccess: '#0F9F47',
            textDanger: '#E14D4D',
            textWarning: '#B7791F',
            textOnAccent: '#FFFFFF',
            borderSubtle: '#D7E3F4',
            borderStrong: '#8FB6F0',
            buttonPrimary: '#0E5DCC',
            buttonPrimaryText: '#FFFFFF',
            buttonSecondary: '#FFFFFF',
            buttonSecondaryText: '#0A1F44',
            buttonSecondaryBorder: '#C9D9F0',
            buttonGhost: '#E1ECFA',
            buttonGhostText: '#23406A',
            timelinePill: '#DBECFF',
            timelinePillText: '#0A58BA',
            rankBadge: '#BED7FF',
            rankBadgeText: '#0A4B9C',
            mapZone: '#1B4075',
            mapZoneStrong: '#0E5DCC',
            mapZoneText: '#F4F8FF',
            bullet: '#0E5DCC',
            overlayBackdrop: 'rgba(6, 37, 86, 0.32)',
        },
    },
    dark: {
        id: 'blue-2024',
        mode: 'dark',
        colors: {
            appBackground: '#031633',
            navigationBackground: '#3C4E69',
            navigationBorder: 'rgba(255, 255, 255, 0.08)',
            navigationActive: '#6A72FF',
            navigationInactive: '#D2E1F7',
            navigationBackdrop: '#4B5A70',
            navigationSurface: '#08213F',
            navigationShadow: '#000814',
            navigationScrim: '#020B19',
            menuBackground: '#4A5A75',
            menuPanel: '#5A6A84',
            sheetBackground: '#0A2850',
            sheetHandle: '#335D91',
            headerActionBackground: '#113563',
            headerActionForeground: '#D2E1F7',
            surfacePrimary: '#0A2850',
            surfaceMuted: '#113563',
            surfaceAccent: '#123E7A',
            surfaceAccentStrong: '#3B82F6',
            surfaceInverse: '#F4F8FF',
            surfaceSuccess: '#0D4B2D',
            surfaceDanger: '#6B1F2A',
            surfaceWarning: '#5C3B11',
            textPrimary: '#F4F8FF',
            textSecondary: '#D2E1F7',
            textMuted: '#9FB7DA',
            textInverse: '#0A1F44',
            textBrand: '#93C5FD',
            textSuccess: '#8CE99A',
            textDanger: '#FFB4B4',
            textWarning: '#FFD27A',
            textOnAccent: '#FFFFFF',
            borderSubtle: '#23406A',
            borderStrong: '#3B82F6',
            buttonPrimary: '#3B82F6',
            buttonPrimaryText: '#FFFFFF',
            buttonSecondary: '#0A2850',
            buttonSecondaryText: '#F4F8FF',
            buttonSecondaryBorder: '#335D91',
            buttonGhost: '#113563',
            buttonGhostText: '#D2E1F7',
            timelinePill: '#113563',
            timelinePillText: '#93C5FD',
            rankBadge: '#1E3A5F',
            rankBadgeText: '#BFDBFE',
            mapZone: '#123E7A',
            mapZoneStrong: '#2563EB',
            mapZoneText: '#F4F8FF',
            bullet: '#60A5FA',
            overlayBackdrop: 'rgba(2, 11, 25, 0.6)',
        },
    },
};
