import {type ResolvedThemeMode, type ThemeTokens} from '../types';

export const defaultTheme: Record<ResolvedThemeMode, ThemeTokens> = {
    light: {
        id: 'default',
        mode: 'light',
        colors: {
            appBackground: '#E7ECF7',
            navigationBackground: '#334155',
            navigationBorder: 'rgba(15, 23, 42, 0.12)',
            navigationActive: '#6366F1',
            navigationInactive: '#CBD5E1',
            navigationBackdrop: '#4B5563',
            navigationSurface: '#faf9f5',
            navigationShadow: '#020617',
            navigationScrim: '#020617',
            menuBackground: '#f0eee6',
            menuPanel: '#6B7280',
            sheetBackground: '#FFFFFF',
            sheetHandle: '#CBD5E1',
            headerActionBackground: '#F8FAFC',
            headerActionForeground: '#64748B',
            surfacePrimary: '#FFFFFF',
            surfaceMuted: '#F8FAFC',
            surfaceAccent: '#DBEAFE',
            surfaceAccentStrong: '#1D4ED8',
            surfaceInverse: '#0F172A',
            surfaceSuccess: '#DCFCE7',
            surfaceDanger: '#FEE2E2',
            surfaceWarning: '#FEF3C7',
            textPrimary: '#0F172A',
            textSecondary: '#334155',
            textMuted: '#64748B',
            textInverse: '#F8FAFC',
            textBrand: '#93C5FD',
            textSuccess: '#15803D',
            textDanger: '#DC2626',
            textWarning: '#B45309',
            textOnAccent: '#FFFFFF',
            borderSubtle: '#E2E8F0',
            borderStrong: '#93C5FD',
            buttonPrimary: '#0F172A',
            buttonPrimaryText: '#FFFFFF',
            buttonSecondary: '#FFFFFF',
            buttonSecondaryText: '#0F172A',
            buttonSecondaryBorder: '#E2E8F0',
            buttonGhost: '#F1F5F9',
            buttonGhostText: '#475569',
            timelinePill: '#E0F2FE',
            timelinePillText: '#0369A1',
            timetableGridLine: 'rgba(2, 15, 149, 0.2)',
            timetableTimeLine: '#111646',
            timetableCardBackground: 'rgba(0, 13, 145, 0.8)',
            timetableCardParticipant: 'rgba(240, 178, 8, 0.8)',
            timetableCardTextDark: '#111646',
            timetableLabelAccent: '#FFB400',
            timetablePastOverlay: 'rgba(2, 15, 149, 0.1)',
            rankBadge: '#FDE68A',
            rankBadgeText: '#92400E',
            mapZone: '#1E293B',
            mapZoneStrong: '#1D4ED8',
            mapZoneText: '#F8FAFC',
            bullet: '#2563EB',
            overlayBackdrop: 'rgba(15, 23, 42, 0.36)',
        },
    },
    dark: {
        id: 'default',
        mode: 'dark',
        colors: {
            appBackground: '#020617',
            navigationBackground: '#374151',
            navigationBorder: 'rgba(255, 255, 255, 0.08)',
            navigationActive: '#6366F1',
            navigationInactive: '#CBD5E1',
            navigationBackdrop: '#4B5563',
            navigationSurface: '#242626',
            navigationShadow: '#000000',
            navigationScrim: '#020617',
            menuBackground: '#141413',
            menuPanel: '#6B7280',
            sheetBackground: '#242626',
            sheetHandle: '#334155',
            headerActionBackground: '#1E293B',
            headerActionForeground: '#CBD5E1',
            surfacePrimary: '#111827',
            surfaceMuted: '#1E293B',
            surfaceAccent: '#172554',
            surfaceAccentStrong: '#2563EB',
            surfaceInverse: '#F8FAFC',
            surfaceSuccess: '#14532D',
            surfaceDanger: '#7F1D1D',
            surfaceWarning: '#78350F',
            textPrimary: '#F8FAFC',
            textSecondary: '#CBD5E1',
            textMuted: '#94A3B8',
            textInverse: '#0F172A',
            textBrand: '#60A5FA',
            textSuccess: '#86EFAC',
            textDanger: '#FCA5A5',
            textWarning: '#FCD34D',
            textOnAccent: '#FFFFFF',
            borderSubtle: '#334155',
            borderStrong: '#2563EB',
            buttonPrimary: '#2563EB',
            buttonPrimaryText: '#FFFFFF',
            buttonSecondary: '#111827',
            buttonSecondaryText: '#F8FAFC',
            buttonSecondaryBorder: '#334155',
            buttonGhost: '#1E293B',
            buttonGhostText: '#CBD5E1',
            timelinePill: '#082F49',
            timelinePillText: '#7DD3FC',
            timetableGridLine: 'rgba(147, 197, 253, 0.24)',
            timetableTimeLine: '#DBEAFE',
            timetableCardBackground: 'rgba(37, 99, 235, 0.8)',
            timetableCardParticipant: 'rgba(240, 178, 8, 0.8)',
            timetableCardTextDark: '#111646',
            timetableLabelAccent: '#FCD34D',
            timetablePastOverlay: 'rgba(147, 197, 253, 0.08)',
            rankBadge: '#713F12',
            rankBadgeText: '#FCD34D',
            mapZone: '#1E293B',
            mapZoneStrong: '#1D4ED8',
            mapZoneText: '#F8FAFC',
            bullet: '#60A5FA',
            overlayBackdrop: 'rgba(2, 6, 23, 0.58)',
        },
    },
};
