import {type ResolvedThemeMode, type ThemeId, type ThemeTokens} from './types';

type ThemeCatalog = Record<ThemeId, Record<ResolvedThemeMode, ThemeTokens>>;

const themeCatalog: ThemeCatalog = {
    default: {
        light: {
            id: 'default',
            mode: 'light',
            colors: {
                appBackground: '#E7ECF7',
                navigationBackground: '#0F172A',
                navigationBorder: 'rgba(255, 255, 255, 0.08)',
                navigationActive: '#6366F1',
                navigationInactive: '#94A3B8',
                stageBackdrop: '#020617',
                stageSurface: '#E7ECF7',
                stageShadow: '#020617',
                stageScrim: '#020617',
                menuBackground: '#020617',
                menuPanel: '#0F172A',
                sheetBackground: '#FFFFFF',
                sheetHandle: '#CBD5E1',
                headerActionBackground: '#F8FAFC',
                headerActionForeground: '#64748B',
                surfacePrimary: '#FFFFFF',
                surfaceMuted: '#F8FAFC',
                surfaceAccent: '#DBEAFE',
                surfaceAccentStrong: '#1D4ED8',
                surfaceInverse: '#0F172A',
                surfaceSuccess: '#DCFCE7',
                surfaceDanger: '#FEE2E2',
                surfaceWarning: '#FEF3C7',
                textPrimary: '#0F172A',
                textSecondary: '#334155',
                textMuted: '#64748B',
                textInverse: '#F8FAFC',
                textBrand: '#93C5FD',
                textSuccess: '#15803D',
                textDanger: '#DC2626',
                textWarning: '#B45309',
                textOnAccent: '#FFFFFF',
                borderSubtle: '#E2E8F0',
                borderStrong: '#93C5FD',
                buttonPrimary: '#0F172A',
                buttonPrimaryText: '#FFFFFF',
                buttonSecondary: '#FFFFFF',
                buttonSecondaryText: '#0F172A',
                buttonSecondaryBorder: '#E2E8F0',
                buttonGhost: '#F1F5F9',
                buttonGhostText: '#475569',
                timelinePill: '#E0F2FE',
                timelinePillText: '#0369A1',
                rankBadge: '#FDE68A',
                rankBadgeText: '#92400E',
                mapZone: '#1E293B',
                mapZoneStrong: '#1D4ED8',
                mapZoneText: '#F8FAFC',
                bullet: '#2563EB',
                overlayBackdrop: 'rgba(15, 23, 42, 0.36)',
            },
        },
        dark: {
            id: 'default',
            mode: 'dark',
            colors: {
                appBackground: '#020617',
                navigationBackground: '#0B1220',
                navigationBorder: 'rgba(255, 255, 255, 0.08)',
                navigationActive: '#6366F1',
                navigationInactive: '#94A3B8',
                stageBackdrop: '#01030A',
                stageSurface: '#0F172A',
                stageShadow: '#000000',
                stageScrim: '#020617',
                menuBackground: '#020617',
                menuPanel: '#111827',
                sheetBackground: '#111827',
                sheetHandle: '#334155',
                headerActionBackground: '#1E293B',
                headerActionForeground: '#CBD5E1',
                surfacePrimary: '#111827',
                surfaceMuted: '#1E293B',
                surfaceAccent: '#172554',
                surfaceAccentStrong: '#2563EB',
                surfaceInverse: '#F8FAFC',
                surfaceSuccess: '#14532D',
                surfaceDanger: '#7F1D1D',
                surfaceWarning: '#78350F',
                textPrimary: '#F8FAFC',
                textSecondary: '#CBD5E1',
                textMuted: '#94A3B8',
                textInverse: '#0F172A',
                textBrand: '#60A5FA',
                textSuccess: '#86EFAC',
                textDanger: '#FCA5A5',
                textWarning: '#FCD34D',
                textOnAccent: '#FFFFFF',
                borderSubtle: '#334155',
                borderStrong: '#2563EB',
                buttonPrimary: '#2563EB',
                buttonPrimaryText: '#FFFFFF',
                buttonSecondary: '#111827',
                buttonSecondaryText: '#F8FAFC',
                buttonSecondaryBorder: '#334155',
                buttonGhost: '#1E293B',
                buttonGhostText: '#CBD5E1',
                timelinePill: '#082F49',
                timelinePillText: '#7DD3FC',
                rankBadge: '#713F12',
                rankBadgeText: '#FCD34D',
                mapZone: '#1E293B',
                mapZoneStrong: '#1D4ED8',
                mapZoneText: '#F8FAFC',
                bullet: '#60A5FA',
                overlayBackdrop: 'rgba(2, 6, 23, 0.58)',
            },
        },
    },
    'blue-2024': {
        light: {
            id: 'blue-2024',
            mode: 'light',
            colors: {
                appBackground: '#EAF2FF',
                navigationBackground: '#0A1F44',
                navigationBorder: 'rgba(255, 255, 255, 0.08)',
                navigationActive: '#5B5FFF',
                navigationInactive: '#A8B7D3',
                stageBackdrop: '#031633',
                stageSurface: '#EDF4FF',
                stageShadow: '#031633',
                stageScrim: '#062556',
                menuBackground: '#031633',
                menuPanel: '#0C2B5A',
                sheetBackground: '#FFFFFF',
                sheetHandle: '#B6C7E3',
                headerActionBackground: '#F5F9FF',
                headerActionForeground: '#6A7EA3',
                surfacePrimary: '#FFFFFF',
                surfaceMuted: '#F5F9FF',
                surfaceAccent: '#D8E8FF',
                surfaceAccentStrong: '#0E5DCC',
                surfaceInverse: '#082F66',
                surfaceSuccess: '#DDF7E8',
                surfaceDanger: '#FCE1E1',
                surfaceWarning: '#FEECC7',
                textPrimary: '#0A1F44',
                textSecondary: '#29466F',
                textMuted: '#5B769D',
                textInverse: '#F4F8FF',
                textBrand: '#8FB6F0',
                textSuccess: '#0F9F47',
                textDanger: '#E14D4D',
                textWarning: '#B7791F',
                textOnAccent: '#FFFFFF',
                borderSubtle: '#D7E3F4',
                borderStrong: '#8FB6F0',
                buttonPrimary: '#0E5DCC',
                buttonPrimaryText: '#FFFFFF',
                buttonSecondary: '#FFFFFF',
                buttonSecondaryText: '#0A1F44',
                buttonSecondaryBorder: '#C9D9F0',
                buttonGhost: '#E1ECFA',
                buttonGhostText: '#23406A',
                timelinePill: '#DBECFF',
                timelinePillText: '#0A58BA',
                rankBadge: '#BED7FF',
                rankBadgeText: '#0A4B9C',
                mapZone: '#1B4075',
                mapZoneStrong: '#0E5DCC',
                mapZoneText: '#F4F8FF',
                bullet: '#0E5DCC',
                overlayBackdrop: 'rgba(6, 37, 86, 0.32)',
            },
        },
        dark: {
            id: 'blue-2024',
            mode: 'dark',
            colors: {
                appBackground: '#031633',
                navigationBackground: '#07172F',
                navigationBorder: 'rgba(255, 255, 255, 0.08)',
                navigationActive: '#6A72FF',
                navigationInactive: '#A3B7D8',
                stageBackdrop: '#020B19',
                stageSurface: '#08213F',
                stageShadow: '#000814',
                stageScrim: '#020B19',
                menuBackground: '#020B19',
                menuPanel: '#0A2850',
                sheetBackground: '#0A2850',
                sheetHandle: '#335D91',
                headerActionBackground: '#113563',
                headerActionForeground: '#D2E1F7',
                surfacePrimary: '#0A2850',
                surfaceMuted: '#113563',
                surfaceAccent: '#123E7A',
                surfaceAccentStrong: '#3B82F6',
                surfaceInverse: '#F4F8FF',
                surfaceSuccess: '#0D4B2D',
                surfaceDanger: '#6B1F2A',
                surfaceWarning: '#5C3B11',
                textPrimary: '#F4F8FF',
                textSecondary: '#D2E1F7',
                textMuted: '#9FB7DA',
                textInverse: '#0A1F44',
                textBrand: '#93C5FD',
                textSuccess: '#8CE99A',
                textDanger: '#FFB4B4',
                textWarning: '#FFD27A',
                textOnAccent: '#FFFFFF',
                borderSubtle: '#23406A',
                borderStrong: '#3B82F6',
                buttonPrimary: '#3B82F6',
                buttonPrimaryText: '#FFFFFF',
                buttonSecondary: '#0A2850',
                buttonSecondaryText: '#F4F8FF',
                buttonSecondaryBorder: '#335D91',
                buttonGhost: '#113563',
                buttonGhostText: '#D2E1F7',
                timelinePill: '#113563',
                timelinePillText: '#93C5FD',
                rankBadge: '#1E3A5F',
                rankBadgeText: '#BFDBFE',
                mapZone: '#123E7A',
                mapZoneStrong: '#2563EB',
                mapZoneText: '#F4F8FF',
                bullet: '#60A5FA',
                overlayBackdrop: 'rgba(2, 11, 25, 0.6)',
            },
        },
    },
};

export function resolveTheme(themeId: ThemeId, mode: ResolvedThemeMode): ThemeTokens {
    return themeCatalog[themeId][mode];
}

export const availableThemes: Array<{id: ThemeId; label: string}> = [
    {id: 'default', label: 'Default'},
    {id: 'blue-2024', label: 'Blue 2024'},
];
