export type ThemeMode = 'system' | 'light' | 'dark';
export type ResolvedThemeMode = 'light' | 'dark';
export type ThemeId = 'default' | 'blue-2024';

export type ThemeTokens = {
    id: ThemeId;
    mode: ResolvedThemeMode;
    colors: {
        appBackground: string;
        navigationBackground: string;
        navigationBorder: string;
        navigationActive: string;
        navigationInactive: string;
        stageBackdrop: string;
        stageSurface: string;
        stageShadow: string;
        stageScrim: string;
        menuBackground: string;
        menuPanel: string;
        sheetBackground: string;
        sheetHandle: string;
        headerActionBackground: string;
        headerActionForeground: string;
        surfacePrimary: string;
        surfaceMuted: string;
        surfaceAccent: string;
        surfaceAccentStrong: string;
        surfaceInverse: string;
        surfaceSuccess: string;
        surfaceDanger: string;
        surfaceWarning: string;
        textPrimary: string;
        textSecondary: string;
        textMuted: string;
        textInverse: string;
        textBrand: string;
        textSuccess: string;
        textDanger: string;
        textWarning: string;
        textOnAccent: string;
        borderSubtle: string;
        borderStrong: string;
        buttonPrimary: string;
        buttonPrimaryText: string;
        buttonSecondary: string;
        buttonSecondaryText: string;
        buttonSecondaryBorder: string;
        buttonGhost: string;
        buttonGhostText: string;
        timelinePill: string;
        timelinePillText: string;
        rankBadge: string;
        rankBadgeText: string;
        mapZone: string;
        mapZoneStrong: string;
        mapZoneText: string;
        bullet: string;
        overlayBackdrop: string;
    };
};
